[project]
name = "yakof"
version = "0.1.0"
description = "A technology demonstrator for sustainability modeling"
requires-python = "==3.11.11"
dependencies = ["scipy", "dt-model", "numpy", "sympy"]
license = "Apache-2.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["black>=24.10.0", "pytest>=7.0.0", "pytest-cov>=4.0.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "--cov=yakof --cov-report=xml --cov-report=term-missing"

[tool.uv.sources]
dt-model = { git = "https://github.com/fbk-most/dt-model", rev = "main" }
