"""
Canonical Bases.
===============

This module defines the canonical bases for tensor spaces up to R⁶,
using the canonical dimensions X, Y, Z, U, V, and W.

Each basis defines its axes as a set of integers following the canonical
ordering generated by morphisms.generate_canonical axes.

Bases
-----

- R⁰: scalar
- R¹: X, Y, Z, U, V, W (single axes)
- R²: XY, XZ, YZ, ... (15 pairs of axes)
- R³: XYZ, XYU, ... (20 combinations)
- R⁴: XYZU, ... (15 combinations)
- R⁵: XYZUV, ... (6 combinations)
- R⁶: XYZUVW (1 combination)
"""

from . import morphisms

# Get canonical axes
x_axis_id, y_axis_id, z_axis_id, u_axis_id, v_axis_id, w_axis_id = morphisms.generate_canonical_axes(6)


# R⁰ basis
class Scalar:
    """Tensor basis for scalar values (0-dimensional tensors)."""

    axes = ()


# R¹ bases
class X:
    """Tensor basis along the X axis."""

    axes = (x_axis_id,)


class Y:
    """Tensor basis along the Y axis."""

    axes = (y_axis_id,)


class Z:
    """Tensor basis along the Z axis."""

    axes = (z_axis_id,)


class U:
    """Tensor basis along the U axis."""

    axes = (u_axis_id,)


class V:
    """Tensor basis along the V axis."""

    axes = (v_axis_id,)


class W:
    """Tensor basis along the W axis."""

    axes = (w_axis_id,)


# R² bases
class XY:
    """Tensor basis along X and Y axes."""

    axes = (x_axis_id, y_axis_id)


class XZ:
    """Tensor basis along X and Z axes."""

    axes = (x_axis_id, z_axis_id)


class XU:
    """Tensor basis along X and U axes."""

    axes = (x_axis_id, u_axis_id)


class XV:
    """Tensor basis along X and V axes."""

    axes = (x_axis_id, v_axis_id)


class XW:
    """Tensor basis along X and W axes."""

    axes = (x_axis_id, w_axis_id)


class YZ:
    """Tensor basis along Y and Z axes."""

    axes = (y_axis_id, z_axis_id)


class YU:
    """Tensor basis along Y and U axes."""

    axes = (y_axis_id, u_axis_id)


class YV:
    """Tensor basis along Y and V axes."""

    axes = (y_axis_id, v_axis_id)


class YW:
    """Tensor basis along Y and W axes."""

    axes = (y_axis_id, w_axis_id)


class ZU:
    """Tensor basis along Z and U axes."""

    axes = (z_axis_id, u_axis_id)


class ZV:
    """Tensor basis along Z and V axes."""

    axes = (z_axis_id, v_axis_id)


class ZW:
    """Tensor basis along Z and W axes."""

    axes = (z_axis_id, w_axis_id)


class UV:
    """Tensor basis along U and V axes."""

    axes = (u_axis_id, v_axis_id)


class UW:
    """Tensor basis along U and W axes."""

    axes = (u_axis_id, w_axis_id)


class VW:
    """Tensor basis along V and W axes."""

    axes = (v_axis_id, w_axis_id)


# R³ bases
class XYZ:
    """Tensor basis along X, Y and Z axes."""

    axes = (x_axis_id, y_axis_id, z_axis_id)


class XYU:
    """Tensor basis along X, Y and U axes."""

    axes = (x_axis_id, y_axis_id, u_axis_id)


class XYV:
    """Tensor basis along X, Y and V axes."""

    axes = (x_axis_id, y_axis_id, v_axis_id)


class XYW:
    """Tensor basis along X, Y and W axes."""

    axes = (x_axis_id, y_axis_id, w_axis_id)


class XZU:
    """Tensor basis along X, Z and U axes."""

    axes = (x_axis_id, z_axis_id, u_axis_id)


class XZV:
    """Tensor basis along X, Z and V axes."""

    axes = (x_axis_id, z_axis_id, v_axis_id)


class XZW:
    """Tensor basis along X, Z and W axes."""

    axes = (x_axis_id, z_axis_id, w_axis_id)


class XUV:
    """Tensor basis along X, U and V axes."""

    axes = (x_axis_id, u_axis_id, v_axis_id)


class XUW:
    """Tensor basis along X, U and W axes."""

    axes = (x_axis_id, u_axis_id, w_axis_id)


class XVW:
    """Tensor basis along X, V and W axes."""

    axes = (x_axis_id, v_axis_id, w_axis_id)


class YZU:
    """Tensor basis along Y, Z and U axes."""

    axes = (y_axis_id, z_axis_id, u_axis_id)


class YZV:
    """Tensor basis along Y, Z and V axes."""

    axes = (y_axis_id, z_axis_id, v_axis_id)


class YZW:
    """Tensor basis along Y, Z and W axes."""

    axes = (y_axis_id, z_axis_id, w_axis_id)


class YUV:
    """Tensor basis along Y, U and V axes."""

    axes = (y_axis_id, u_axis_id, v_axis_id)


class YUW:
    """Tensor basis along Y, U and W axes."""

    axes = (y_axis_id, u_axis_id, w_axis_id)


class YVW:
    """Tensor basis along Y, V and W axes."""

    axes = (y_axis_id, v_axis_id, w_axis_id)


class ZUV:
    """Tensor basis along Z, U and V axes."""

    axes = (z_axis_id, u_axis_id, v_axis_id)


class ZUW:
    """Tensor basis along Z, U and W axes."""

    axes = (z_axis_id, u_axis_id, w_axis_id)


class ZVW:
    """Tensor basis along Z, V and W axes."""

    axes = (z_axis_id, v_axis_id, w_axis_id)


class UVW:
    """Tensor basis along U, V and W axes."""

    axes = (u_axis_id, v_axis_id, w_axis_id)


# R⁴ bases
class XYZU:
    """Tensor basis along X, Y, Z and U axes."""

    axes = (x_axis_id, y_axis_id, z_axis_id, u_axis_id)


class XYZV:
    """Tensor basis along X, Y, Z and V axes."""

    axes = (x_axis_id, y_axis_id, z_axis_id, v_axis_id)


class XYZW:
    """Tensor basis along X, Y, Z and W axes."""

    axes = (x_axis_id, y_axis_id, z_axis_id, w_axis_id)


class XYUV:
    """Tensor basis along X, Y, U and V axes."""

    axes = (x_axis_id, y_axis_id, u_axis_id, v_axis_id)


class XYUW:
    """Tensor basis along X, Y, U and W axes."""

    axes = (x_axis_id, y_axis_id, u_axis_id, w_axis_id)


class XYVW:
    """Tensor basis along X, Y, V and W axes."""

    axes = (x_axis_id, y_axis_id, v_axis_id, w_axis_id)


class XZUV:
    """Tensor basis along X, Z, U and V axes."""

    axes = (x_axis_id, z_axis_id, u_axis_id, v_axis_id)


class XZUW:
    """Tensor basis along X, Z, U and W axes."""

    axes = (x_axis_id, z_axis_id, u_axis_id, w_axis_id)


class XZVW:
    """Tensor basis along X, Z, V and W axes."""

    axes = (x_axis_id, z_axis_id, v_axis_id, w_axis_id)


class XUVW:
    """Tensor basis along X, U, V and W axes."""

    axes = (x_axis_id, u_axis_id, v_axis_id, w_axis_id)


class YZUV:
    """Tensor basis along Y, Z, U and V axes."""

    axes = (y_axis_id, z_axis_id, u_axis_id, v_axis_id)


class YZUW:
    """Tensor basis along Y, Z, U and W axes."""

    axes = (y_axis_id, z_axis_id, u_axis_id, w_axis_id)


class YZVW:
    """Tensor basis along Y, Z, V and W axes."""

    axes = (y_axis_id, z_axis_id, v_axis_id, w_axis_id)


class YUVW:
    """Tensor basis along Y, U, V and W axes."""

    axes = (y_axis_id, u_axis_id, v_axis_id, w_axis_id)


class ZUVW:
    """Tensor basis along Z, U, V and W axes."""

    axes = (z_axis_id, u_axis_id, v_axis_id, w_axis_id)


# R⁵ bases
class XYZUV:
    """Tensor basis along X, Y, Z, U and V axes."""

    axes = (x_axis_id, y_axis_id, z_axis_id, u_axis_id, v_axis_id)


class XYZUW:
    """Tensor basis along X, Y, Z, U and W axes."""

    axes = (x_axis_id, y_axis_id, z_axis_id, u_axis_id, w_axis_id)


class XYZVW:
    """Tensor basis along X, Y, Z, V and W axes."""

    axes = (x_axis_id, y_axis_id, z_axis_id, v_axis_id, w_axis_id)


class XYUVW:
    """Tensor basis along X, Y, U, V and W axes."""

    axes = (x_axis_id, y_axis_id, u_axis_id, v_axis_id, w_axis_id)


class XZUVW:
    """Tensor basis along X, Z, U, V and W axes."""

    axes = (x_axis_id, z_axis_id, u_axis_id, v_axis_id, w_axis_id)


class YZUVW:
    """Tensor basis along Y, Z, U, V and W axes."""

    axes = (y_axis_id, z_axis_id, u_axis_id, v_axis_id, w_axis_id)


# R⁶ basis
class XYZUVW:
    """Tensor basis along X, Y, Z, U, V and W axes."""

    axes = (x_axis_id, y_axis_id, z_axis_id, u_axis_id, v_axis_id, w_axis_id)
